# traefik-ingressroute-simple.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: caddy-local-routes
  namespace: proxy
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`casaos.local`) || Host(`net.local`) || Host(`proxmox.local`)
    kind: Rule
    services:
    - name: caddy-internal
      port: 80
