apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axis-zero-nginx-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: axis-zero-app 
  namespaceSelector:
    matchNames:
      - axis-zero
  endpoints:
  - port: nginx-metrics  # Scrapeson port 9113
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
