apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axis-zero-cloudflared-tunnel
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cloudflared-tunnel
  namespaceSelector:
    - axis-zero
  endpoints:
  - port: metrics  # Scrapes on port 20241
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  namespaceSelector:
    any: true
    